### PR TITLE
Feat: rename unsuitable file names externalDb.*

### LINKED ISSUE #747: Rename files to reflect their functionality
**Please describe the feature**
As a developer, I want file names to reflect their functionality so that I can easily understand the code base

**Describe the solution you'd like**
`frontend/src/components/ExternalDb.vue` and `frontend/src/store/modules/externalDb.js` is related to `/identifier/:dbName/:identifierId`, i.e. search for the occurrence of external identifier within the models. `frontend/src/components/IdInModels.vue` is a possible new name, since we use the code both for searching for identifiers within Metabolic Atlas and identifiers from external databases in the models.

**Additional context**
Suggestion for new name originated from https://github.com/MetabolicAtlas/MetabolicAtlas/issues/608#issuecomment-957436639

This issue is only about a single renaming case, other should be dealt with separately.

### PR DESCRIPTION
**Pull request by nanjiangshu**
**Related issue(s) and PR(s)**  
This PR closes #747 

**Type of change**  

- [x] refactoring
 
**List of changes made**  

The vue file `frontend/src/components/ExternalDb.vue` is renamed as `IdInModels.vue`
The following js files
```
frontend/src/store/modules/externalDb.js
frontend/src/api/externalDb.js
api/src/neo4j/queries/externalDb.js
```
 are renamed as `idInModels.js`

**Screenshot of the fix**  

**Testing**  

- Instructions on how to test
Test if the following urls return expected result
http://localhost/identifier/BiGG/DST_ANTIGENt
http://localhost/identifier/MetabolicAtlas/MAM03785m

**Further comments**  

**Definition of Done checklist**  
- [ ] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by nanjiangshu** [comment]
I set this PR as draft is because I found there are many places, both at the frontend and the API, the variable `externalDb` is used. I'm not sure if this issue should be extended from renaming file names to renaming all occurrences of `externalDb` in the code base. 
Moreover, the API endpoint `/external-db/:dbName/:externalId` is also not very appropriate if we think `externalDb.js` is not suitable. But if we change that API endpoint, may it break other web-services that use this API?

**Comment by mihai-sysbio** [comment]
> may it break other web-services that use this API?

That is acceptable.

**Comment by nanjiangshu** [comment]
After discussion at the standup today, @MalinAhlberg and me think it is reasonable to restrict the issue to what is described, that is only change the file names. A new issue will be created to address the renaming of all related variables as well as the API endpoint `/external-db/:dbName/:externalId`, if the others also agree.

**Review by inghylt — APPROVED** [review]
I think this makes things clearer! Please communicate when the mentioned new issue is created so that's not forgotten

**Comment by nanjiangshu** [comment]
> I think this makes things clearer! Please communicate when the mentioned new issue is created so that's not forgotten

Two new issues #994 and #995 are created to address the renaming of variables and the API endpoint.

**Review by MalinAhlberg — APPROVED** [review]
Looks good to me!

**Pull request merged**
