### PR TITLE
fix: remove ko

### LINKED ISSUE #1089: Remove KO from input_dara
**Please describe the feature**

As a researcher, I want to remove the KO data from the gotenzymes db so that the project only uses data that is supposed to be available.

**Acceptance Criteria**

- [ ] Remove KO from the input_data
- [ ] Redeploy with the updated input_data

**Additional context**

### PR DESCRIPTION
**Pull request by mihai-sysbio**
**Related issue(s) and PR(s)**  
This PR closes #1089.

**Type of change**  

**List of changes made**  

Remove `ko` from the columns expected as input to the psql database.

**Testing**  

- A certain branch in other repos is needed
- A rebuild is needed due to new dependencies: make sure to [reimport GotEnzymes](https://github.com/MetabolicAtlas/MetabolicAtlas/#gotenzymes)
- Instructions on how to test: play around on GotEnzymes

**Further comments**  

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Thanks for the review @MalinAhlberg.

> * is it ok to add the link to the data to [the instructions](/Human-GEM/interaction-partners/ENSG00000185000) so that it's easy to find?

That link is password-protected, but not meant to be public.

> * is the new data what's deployed to the new prod server?

Yes.

**Comment by MalinAhlberg** [comment]
> > * is it ok to add the link to the data to [the instructions](https://github.com/MetabolicAtlas/MetabolicAtlas/#gotenzymes) so that it's easy to find?
> 
> That link is password-protected, but not meant to be public.

So, that's a no then? :upside_down_face:

**Review by MalinAhlberg — APPROVED** [review]
Looks good!

**Comment by mihai-sysbio** [comment]
> So, that's a no then? 🙃

As far as I can see, it is and will continue to be the case that the source database files will not be public. There is an issue, however, that would cover the automatic import of these data #1087.

**Review by nanjiangshu — APPROVED** [review]
LGTM!

**Review by e0 — APPROVED** [review]

**Pull request merged**
