### PR TITLE
fix: create folder api/repository if it does not exist

### PR DESCRIPTION
**Pull request by nanjiangshu**
Create the folder `api/repository` if it does not exist (which is the case after a fresh clone), otherwise, the command ```/bin/cp -r $DATA_FILES_PATH/ftp-models/* api/repository/``` will end up in an error.

### CODE REVIEW

**Review by e0 — APPROVED** [review]
Nice catch!

**Review by mihai-sysbio — CHANGES_REQUESTED** [review]
This case seems conceptually identical with that on line `12` above. Wouldn't it be simpler to rename the `ftp-models` folder in `data-files` to `repository`?
Also, `ftp-models` is a name we don't use so much - imho, it add confusion, so I support renaming it regardless of the current issue.

**Review by inghylt — APPROVED** [review]

**Comment by nanjiangshu** [comment]
> This case seems conceptually identical with that on line `12` above. Wouldn't it be simpler to rename the `ftp-models` folder in `data-files` to `repository`?
> Also, `ftp-models` is a name we don't use so much - imho, it adds confusion, so I support renaming it regardless of the current issue.

@mihai-sysbio , Good point! I think it is less confusion if name `ftp-models` to `repository`, then we have the same name for the folder containing downloadable models. Actually, we may copy these models only at one place and the other one just create a symlink. 

However, if we rename `ftp-models` to `repository`, it means the folder `ftp/ftp-models/` will not be existing anymore. The path to this folder needs to be changed at other places as well. Except for the file `ftp/Dockerfile`, do you know other places to be changed?

**Comment by mihai-sysbio** [comment]
`proj.sh` comes to mind, but since it's a unique name a find+replace should do.

**Review by e0 — CHANGES_REQUESTED** [review]
Please add `ftp/repository/` to the `.gitignore` file.

**Review by e0 — APPROVED** [review]

**Comment by nanjiangshu** [comment]
> Please add `ftp/repository/` to the `.gitignore` file.

Done! 

P.S. I'm sorry that I have pushed this commit to your branch `feat/interaction-partners-layout_MA-936` but not reverted.

**Comment by e0** [comment]
> > Please add `ftp/repository/` to the `.gitignore` file.
> 
> Done!
> 
> P.S. I'm sorry that I have pushed this commit to your branch `feat/interaction-partners-layout_MA-936` but not reverted.

No worries but thanks for mentioning it. I can do a force push to remove it.

**Comment by nanjiangshu** [comment]
> > > Please add `ftp/repository/` to the `.gitignore` file.
> > 
> > 
> > Done!
> > P.S. I'm sorry that I have pushed this commit to your branch `feat/interaction-partners-layout_MA-936` but not reverted.
> 
> No worries but thanks for mentioning it. I can do a force push to remove it.

Typo! I mean I have reverted the commit :)

**Review by mihai-sysbio — APPROVED** [review]
Neat!

**Pull request merged**
