### PR TITLE
fix: map moves on overlay

### LINKED ISSUE #1128: Changing the data overlay in 3D resets the view (coordinates)
**Describe the bug**

When applying data overlay to the 3D viewer, the state of the of the 3D viewer gets reset that is noticeable if the user interacts with the 3D viewer.

**Steps to reproduce**

1. Navigate to the 3D viewer (a small map loads faster).
2. Move the map (or zoom in).
3. Apply any data overlay.
4. Observe that the viewer changed.

**Expected behavior**

- [ ] applying the data overlay should not change the viewer coordinates (so it should look like nothing is "moving")
- [ ] Tests verifying the fix are added

**Screenshots**

**Additional context**

A first check would be to see if the 3D network viewer code _needs_ to be touched.
Should also fix #1176.

### LINKED ISSUE #1176: Labels are offset after selecting a node for Interaction Partners
**Describe the bug**

The labels are offset when click selecting a node for Interaction Partners

**Steps to reproduce**

1. Open the IP for e.g. `ENSG00000144290`
2. Select any node
3. The labels will be offset 

**Expected behavior**

- [ ] Labels will not be offset when selecting a node 

**Screenshots**

#### After selecting

**Additional context**

After expanding the network, labels will not be offset when selecting a node

### PR DESCRIPTION
**Pull request by MalinAhlberg**
**Related issue(s) and PR(s)**  
This PR closes  #1128.

Add color to 3d maps without redrawing the whole graph. Also don't zoom in on selected/highlighted nodes when applying overlay.

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

 
**List of changes made**  

- use new function from 3dviewer to avoid having to regenerate the whole graph
- do not center selected node when applying overlay

**Screenshot of the fix**  

**Testing**  

- This uses the branch [`feat/color-individual-nodes` in 3d-viewer](https://github.com/MetabolicAtlas/3d-network-viewer/compare/main...feat/color-individual-nodes)
- To use it, do:
- 1. Change value for dependency from version number to git branch in `frontend/package.json`.
```json
    "@metabolicatlas/3d-network-viewer": "MetabolicAtlas/3d-network-viewer#feat/color-individual-nodes",
```

- 2.  Install the dependency and build it.
```bash
ma-exec frontend yarn
ma-exec frontend npm --prefix node_modules/@metabolicatlas/3d-network-viewer/ install
ma-exec frontend npm --prefix node_modules/@metabolicatlas/3d-network-viewer/ run build
```
- Try out the 3d maps and the interaction partners, apply overlay, select nodes, search for nodes, reload the page etc.

**Further comments**  

This does not fix #1176, as the additional context in the issues states. If anyone feels like fixing that, feel free!

**Definition of Done checklist**  
- [ ] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by e0 — COMMENTED** [review]
Nice job! I think I can approve this once https://github.com/MetabolicAtlas/3d-network-viewer/pull/61 is merged and `frontend/package.json` is updated.

There is a small weird behavior for me on the Map Viewer. When I select a data set, I need to move my mouse cursor for the colors to update. (Can test this by switching between any data set to `None`). This doesn't happen on Interaction Partners though. Is it like this for anyone else? I can add a video if it's unclear.

**Comment by inghylt** [comment]
> There is a small weird behavior for me on the Map Viewer. When I select a data set, I need to move my mouse cursor for the colors to update. (Can test this by switching between any data set to None). This doesn't happen on Interaction Partners though. Is it like this for anyone else? I can add a video if it's unclear.

I can confirm this!

Also discovered a bug when you apply overlay data (either in 3DV or IP) and then move to a new IP Details page, the console will report `Uncaught (in promise) TypeError: this.controller is null`. Does not seem to create any functional errors though so not a massive problem, Will have  a look at this

Side note: I had problems getting the frontend container to use the specified 3d-network-viewer dependency, it kept using an older version of the `feat/color-individual-nodes` branch. I think it was starting and stopping the stack that finally solved it, but not on the first try(ies) :shrug:

**Comment by MalinAhlberg** [comment]
thanks for the reviews @e0 and @inghylt! I suspect that https://github.com/MetabolicAtlas/3d-network-viewer/pull/61/commits/d47cc7772db0f9621ba996ff38b33145135e4426 might fix the bug @e0 mentioned, but I'm not able to verify it right now :(

**Comment by e0** [comment]
@MalinAhlberg the https://github.com/MetabolicAtlas/3d-network-viewer/commit/d47cc7772db0f9621ba996ff38b33145135e4426 fix works great! Really good job again on such an optimal way to add these changes.

___

> Also discovered a bug when you apply overlay data (either in 3DV or IP) and then move to a new IP Details page, the console will report Uncaught (in promise) TypeError: this.controller is null in Firefox. Does not seem to create any functional errors though so not a massive problem, Will have a look at this

I can verify this too. I guess we can add a guard for it in the `applyColors()` function to prevent it.

image

**Review by e0 — APPROVED** [review]
Great job! I think I can pre-approve this PR in case we want to merge this early tomorrow. I think all that is left to do is to update the package versions and perhaps add a fix like [mentioned here](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1204#issuecomment-1305865093).

**Review by inghylt — APPROVED** [review]
I can confirm that the visual bug is fixed! I'm also pre approving this, but I'll gladly try it out again when package.json is updated as well. Great job!

**Comment by MalinAhlberg** [comment]
Thanks for your reviews! The package file is now updated, by 26c9447.

**Comment by inghylt** [comment]
I can confirm that the package.json update is working well :+1:

**Pull request merged**
