### PR TITLE
fix: implement no index for dev server

### LINKED ISSUE #1215: Redirect metatlas-dev.csbi.chalmers.se to dev.metabolicatlas.org to avoid dev site to be indexed
**Please describe the feature**

As a developer, I want to have one dev domain configuration to avoid duplicated configuration.

**Acceptance Criteria**

- [ ] Implement redirect dev-metatlas.csbi.chalmers.se to dev.metabolicatlas.org (likely through prod.nginx.conf)

**Additional context**

We can't configure settings for search metatlas-dev.csbi.chalmers.se in Cloudflare since we only have the projects metabolicatlas.org and metabolicatlas.com

### PR DESCRIPTION
**Pull request by inghylt**
**Related issue(s) and PR(s)**  
This PR closes #1215 (it should be probably be renamed to do not index any of the dev hosts)

**Type of change**  

- [x] Other
 
**List of changes made**  

- Implement `<meta>` tag which is described here https://github.com/MetabolicAtlas/MetabolicAtlas/issues/860#issuecomment-1302342163

**Screenshot of the fix**  

**Testing**  

- Instructions on how to test
Visit sites such as https://seositecheckup.com/tools/noindex-tag-test and https://www.seoptimer.com/noindex-tags-checker and test if no index is applied for https://dev.metabolicatlas.org/ and https://metatlas-dev.csbi.chalmers.se

**Further comments**  

Me and @nanjiangshu looked into this together and after a lot of testing we concluded that we also need to keep the Cloudflare settings implemented in https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1211 despite the changes introduced in this PR. For some reason, https://dev.metabolicatlas.org/ is indexable even though it has `<meta name="robots" content="noindex, noarchive, nosnippet, noimageindex" />`. We suspect it has something to do with Cloudflare and we know that it has nothing to do with the v-if statement. So, after this PR, neither https://dev.metabolicatlas.org/ and https://metatlas-dev.csbi.chalmers.se will be indexed but not due to the same configuration.

We did not attempt making any changes to `nginx.prod` as suggested by the issue description since we believe it will create weird and circular configuration as discussed during standup 9/12

**Definition of Done checklist**  
- [ ] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by MalinAhlberg — APPROVED** [review]
Good work to figure this out!

It is a bit confusing that the two dev pages have different x-robot-tags, but I trust your research and have no better suggestions, so I approve!

**Review by nanjiangshu — APPROVED** [review]
I suspect tools like SEOtimer does not analyze meta data well for domains mapped by Cloudfare. Double setting sounds a bit clumsy but does the work.

**Comment by inghylt** [comment]
@MalinAhlberg @nanjiangshu I just realized it might be beneficial to document the double configuration in the code since upcoming developers might not be aware of this PR/previous work, do you think we should keep commit 9fb2f7595836c4485897440e3aa5bb50996b1930?

**Comment by MalinAhlberg** [comment]
> @MalinAhlberg @nanjiangshu I just realized it might be beneficial to document the double configuration in the code since upcoming developers might not be aware of this PR/previous work, do you think we should keep commit [9fb2f75](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/9fb2f7595836c4485897440e3aa5bb50996b1930)?

Good idea! I think we should keep the commit.

**Pull request merged**
