### PR TITLE
fix: dependabot updates

### LINKED ISSUE #977: fix Dependabot issues
**Describe the bug**

Dependabot flags vulnerabilities and creates PRs such as: #956, #957, #958, #959, #969

**Acceptance criteria**

- [x] all issues addressed (suggestions: can be via the opened PRs or close them and have a single PR instead)
- [ ] documentation on the process: how to deal with these Dependabot alerts in a timely manner (how often)

**Additional context**

It has happened in the past (once) that a patch version can break functionality.

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #977.

**Type of change**  

- [x] Other
 
**List of changes made**  

Compilation of Dependabot PRs.

**Further comments**  

Handling of other Dependabot alerts that did not have generated PRs.

Dismissed due to false flag (no longer vulnerable):
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/46
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/47
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/48
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/49
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/50
image

Left alone (related to vue-cli, which is planned to be replaced):
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/38
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/39
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/40
- https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot/51

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by e0** [comment]
As @inghylt suggested, here is the draft for the documentation, please feel free to let me know or edit this comment directly if you see any suitable changes.

### Resolving Dependabot alerts

[Dependabots alert](https://github.com/MetabolicAtlas/MetabolicAtlas/security/dependabot) should be handled periodically. If there is any open Dependabot alerts, they can be handled in the following ways. Once the alerts are handled, a summary should be composed and shared with the team.

1. If a PR is automatically created, test it out locally and make sure the project runs as it should. If everything works as expected, request reviewers from the PR page. In case multiple Dependabot PRs are open, one could create a local branch (for example `fix/dependabot-updates`) and cherry-pick the commits from the Dependabot PRs. Then once things are tested, push up this branch and create a PR as usual. Once this is merged it should automatically resolve the related Dependabot PRs.
2. If an alert can be dismissed, for example a false flag from Dependabot, log the reason in the summary and dismiss it from the Dependabot alert page.
3. If an alert should be left alone, for example if there is planned work that might fix it in the future, log the reason in the summary. If suitable, please create a new issue that might solve the alert.

**Comment by inghylt** [comment]
Nice! I think it looks good. I would suggest that we replace `Dependabots alert should be handled periodically.` to `Dependabot alerts should be handled in the beginning of each sprint.` or similar so we have a set time for it. I feel like it makes sense to do it in the beginning of each sprint so we start of with a clean repo. If the others agree on this we could add it to the Scrum Checklist

**Comment by e0** [comment]
> Nice! I think it looks good. I would suggest that we replace `Dependabots alert should be handled periodically.` to `Dependabot alerts should be handled in the beginning of each sprint.` or similar so we have a set time for it. I feel like it makes sense to do it in the beginning of each sprint so we start of with a clean repo. If the others agree on this we could add it to the Scrum Checklist

I think adding it to the end of the sprint (right before production release) makes more sense so that it's more likely we get the latest fixes out to the users as soon as possible. I really like the idea of adding it to the Scrum Checklist!

**Comment by inghylt** [comment]
@e0 Btw why are the ones under "Dismissed due to false flag (no longer vulnerable):" no longer vulnerable? Did Dependabot create them and afterwards mark them as false flags?

And @mihai-sysbio it would be nice to work with #867 soon

**Comment by e0** [comment]
> @e0 Btw why are the ones under "Dismissed due to false flag (no longer vulnerable):" no longer vulnerable? Did Dependabot create them and afterwards mark them as false flags?

Not exactly sure on the reasons here. I looked up this briefly before and found this: https://stackoverflow.com/questions/69859051/dependabot-no-security-update-is-needed-as-ansi-regex-is-no-longer-vulnerable

I want to remember that we had a similar Dependabot alert before, it was one where we had multiple versions of a package in our product and one of them was vulnerable while a more recent and non-vulnerable one was also included.

**Review by MalinAhlberg — APPROVED** [review]
Nice!

**Review by inghylt — APPROVED** [review]

**Comment by e0** [comment]
It took a few minutes but all of the related Dependabot PRs closed themselves. Nice to see this confirmed.

**Comment by e0** [comment]
I have updated the sentence in the docs to `Dependabots alert should be handled near the end of each sprint, before the sprint release.`. Have also updated the scrum checklist, both the template and the current sprint. Please let me know if you like any other changes.

**Pull request merged**
