### PR TITLE
feat: add alumni section

### LINKED ISSUE #905: Alumni subsection in About page
**Please describe the feature**

As a database evaluator, I want get a picture of the workload involved in setting up this resource, so that I don't have to request this information by email.

**Describe the solution you would like**

A subheader on the _Team_ page with profile cards of previous members of the project.
Add previous contributors from GitHub but also make sure the following people are there: Pierre-Etienne Cholley, Martin Norling, Sergiu Netotea, Jorrit Boekel, Lena Hansson.
Also add previous HMA members: Natapol Pornputtapong
We could consider adding time periods.

**Additional context**

- [ ] start the team listing with the project manager
- [ ] re-sort alphabetically by last name (including existing Team members)
- [ ]  re-sort advisors (Rui, Jon, Hao)

### PR DESCRIPTION
**Pull request by MalinAhlberg**
This draft PR for issue #905 is created to demonstrate the work done so far. 

- [X] start the team listing with the project manager
- [X] re-sort team alphabetically by last name
-  [X] add alumni section
- [X] re-sort advisors (Rui, Jon, Hao)
- [X] remove Hao and Virinchi
- [ ] complete info for all alumnis
- [ ] sort alumni alphabetically
- [ ] add note somewhere: "For other small contributions or more details about the contributions, please see our GitHub page"

So far, only Martin and Sergiu have complete information.

The below will be filled once this is undrafted.

------

**Related issue(s) and PR(s)**  
This PR closes #905.

**Type of change**  

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other
 
**List of changes made**  

**Screenshot of the fix**  

**Testing**  

- A certain branch in other repos is needed
- A rebuild is needed due to new dependencies
- Relative urls that can be reused both for production and local testing
- Instructions on how to test

**Further comments**  

**Definition of Done checklist**  
- [ ] My code meets the Acceptance Criteria
- [ ] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [ ] I have performed a self-review of my own code and commented any hard-to-understand areas
- [ ] Tests and lint/format validations are passing
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
@MalinAhlberg a small comment that I don't think I have written down but maybe have said: Virinchi and Hao were never assigned as contributors to the project, so they shouldn't be part of the _Alumni_ section. Perhaps another _Other contributors_? Or just a link somewhere "For other small contributions or more details about the contributions, please see our GitHub page"?

**Comment by MalinAhlberg** [comment]
> @MalinAhlberg a small comment that I don't think I have written down but maybe have said: Virinchi and Hao were never assigned as contributors to the project, so they shouldn't be part of the _Alumni_ section. Perhaps another _Other contributors_? Or just a link somewhere "For other small contributions or more details about the contributions, please see our GitHub page"?

Ah, thanks for the info! I think your last suggestion makes sense, will add that to the to do-list above (feel free to change/update that)

**Review by e0 — APPROVED** [review]
Looks good!

I agree that it's a good idea to merge these ones for now and create another issue to track the other previous contributors.

**Comment by inghylt** [comment]
I think it looks good! I also think it makes sense to merge this for now and update it when we have information about the other previous contributors. I like the suggestion of "For other small contributions or more details about the contributions, please see our GitHub page", but maybe rewrite it to something like "For more detailed information about the contributions to Metabolic Atlas, please see our GitHub page".

**Comment by e0** [comment]
Thanks for reminding of that and rewriting it @inghylt! I think it sounds really good and have added [a commit](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/924/commits/4677cfcf6f68673ea42637549340693e6db95bef) with your suggestion.

**Review by nanjiangshu — COMMENTED** [review]
Great job! I have one question though: is there any special reason to exclude `pecholleyc` from the alumni list?

**Comment by e0** [comment]
> Great job! I have one question though: is there any special reason to exclude `pecholleyc` from the alumni list?

I think it's because we want to get the permission from each previous contributor to include their info (including photo and full name) on the website and we haven't reached out to some of them yet.

**Review by nanjiangshu — APPROVED** [review]
LGTM!

**Comment by e0** [comment]
> Before merging, what about this item - does it make sense to add it now ?
> 
> > * add note somewhere: "For other small contributions or more details about the contributions, please see our GitHub page"

I think this is what was mentioned [here](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/924#issuecomment-1074997084) or do you mean something else?

___

> Also, how do you want to deal with the unfinished aspects of this PR/issue?

Good reminder, I can create a new issue for the other contributors after merging this PR.

**Review by inghylt — APPROVED** [review]
Nice work!

**Comment by e0** [comment]
New issue added here: https://github.com/MetabolicAtlas/MetabolicAtlas/issues/931

**Pull request merged**
