### PR TITLE
fix: no image in prod deployment

### LINKED ISSUE #1162: No image on the About page when deploying to the dev server
**Describe the bug**
<!-- A clear and concise description of what the bug is -->
The images on the About page are missing when deploying to the `dev` server
**Steps to reproduce**
<!-- Please describe in detail how the bug can be reproduced -->

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. Add checklist item(s) and remove examples not applicable -->
- [ ] Images are shown as expected on the About page (also any other places) when deploying to the dev server from Linux (Ubuntu) <!-- Issue specific criteria -->

**Screenshots**
<!-- If applicable, add screenshots/videos to help explain your problem -->

![Screenshot 2022-10-19 at 08.37.36.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/2eca20b7-59a3-4ade-a463-0c0696d2f7c2)
**Additional context**
<!-- Add any other context about the problem here, e.g. if only applicable on certain browsers or devices -->

**Additional info**
Warning message from the log during deployment, not sure if it's related
```
rendering chunks...                                                                                                                                              
dist/assets/interPart-cover.1745b431.jpg   50.62 KiB                                                                                                             
dist/assets/interPart.a5a854bf.mp4         1800.64 KiB                                                                                                           
dist/assets/analyze.694aeb93.jpg           111.38 KiB                                                                                                            
dist/assets/comparison.9a2c016d.jpg        59.21 KiB                                                                                                             
dist/assets/export.97acfdec.jpg            35.91 KiB                                                                                                             
dist/assets/gemBrowser.fd7ad071.jpg        41.06 KiB                                                                                                             
dist/assets/gems.59ae2506.jpg              43.81 KiB                                                                                                             
dist/assets/group_19.f0139e08.jpg          57.42 KiB                                                                                                             
dist/assets/interaction.481548b4.jpg       19.93 KiB                                                                                                             
dist/assets/mapViewer.99da4c7e.jpg         94.49 KiB                                                                                                             
dist/assets/search.3603c489.jpg            47.91 KiB                                                                                                             
dist/index.html                            4.68 KiB                                                                                                              
dist/assets/index.acef00b4.css             8405.09 KiB / gzip: 936.64 KiB                                                                                        
dist/assets/index.1f00fd3b.js              1633.23 KiB / gzip: 476.79 KiB                                                                                        
                                                                                                                                                                 
(!) Some chunks are larger than 500 KiB after minification. Consider:                                                                                            
- Using dynamic import() to code-split the application                                                                                                           
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks                                             
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit. 
```

### PR DESCRIPTION
**Pull request by mihai-sysbio**
**Related issue(s) and PR(s)**  
This PR closes #1162 and other `vite` issues.

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)

**List of changes made**  

**Testing**  

- Relative urls that can be reused both for production and local testing: `/about/platform`
- Instructions on how to test: also check that the transferred css is <40kb, and that there is a single request made for the js code

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
@nanjiangshu thank you for the work in this branch - it was very easy to verify and continue with other fixes that all combined in this PR.

**Comment by nanjiangshu** [comment]
@mihai-sysbio Thanks for creating this PR. It seems the latest commits about css breaks the image visualization as you can see from https://dev-metatlas.bioshu.se/about/platform (deployed from the latest commit of this branch ee279cc7) 
I tried to deploy from the commit 4a90e0d3 before css change and it works well. 

P.S. I deployed to another dev server I set up myself since it failed many times when I tried to deploy to `dev-metatlas.csbi.chalmers.se`. Maybe we were deploying at the same time?

**Comment by mihai-sysbio** [comment]
> Maybe we were deploying at the same time?

extremely likely - I too noticed the deployment was slower than usual, and I was deploying almost back-to-back

**Comment by mihai-sysbio** [comment]
> * also check that the transferred css is <40kb, and that there is a single request made for the js code

A bit more background info on this: before these fixes, some requests were made twice, and the CSS was at 1,1 MB. All in all, about 2,5 MB would have been unnecessarily downloaded by some browsers (maybe 25% of the market share).

**Review by inghylt — APPROVED** [review]
LGMT!

**Review by e0 — APPROVED** [review]
Great job!

**Pull request merged**
