### PR TITLE
2.3

### PR DESCRIPTION
**Pull request by mihai-sysbio**
With this incremental minor release, Metabolic Atlas has focused on improving both the layout and the content on the _About_ page, which now spans multiple sub-pages. Moreover, we have resolved bugs in the GEM Browser and the Map Viewer, and improved the Documentation. In addition, the process of deploying the software stack has seen some much-wanted attention, improving the robustness, thus paving the way for more regular releases.

#### _About_ page
The work started with [a research issue](https://github.com/MetabolicAtlas/private-issues/issues/150), and was followed by:
- #858 
- #859 

#### GEM Browser and Map Viewer
- #741 
- #745
- #832
- [expression level pop-up missing on the Map Viewer](https://github.com/MetabolicAtlas/private-issues/issues/141)

#### Documentation 
- #601
- #602
- #721 
- #738
- [improvement of how sprint reviews and releases are made](https://github.com/MetabolicAtlas/private-issues/issues/144)

#### Software stack
- #719
- #689
- #780
- #824
- #836
- #841 
- #851
- #853

This release relies on https://github.com/MetabolicAtlas/data-files/commit/504ae593d4bbe0694214ba417b160abd92f34713 and https://github.com/MetabolicAtlas/data-generation/commit/e28d3034d46b6dd8cbfe4df487c8e00b132aff6d.

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Because of delays, this PR will be renamed from `2.2.1` to `2.3`. Before merging, the corresponding News entry should be added.

**Comment by e0** [comment]
> Because of delays, this PR will be renamed from `2.2.1` to `2.3`. Before merging, the corresponding News entry should be added.

Don't remember if we specified but did we set a date for feature-freeze for 2.3? It looks like there are PRs that can be continuously merged into `develop` so I'm not sure where we draw the line for 2.3.

**Comment by e0** [comment]
> > Don't remember if we specified but did we set a date for feature-freeze for 2.3? It looks like there are PRs that can be continuously merged into `develop` so I'm not sure where we draw the line for 2.3.
> 
> My impression was that we would leave it until the end of the sprint, to avoid having 2 releases too close one after the other.

Ok thanks. I guess we can discuss this in more details next week as well if we officially setup a new sprint routine.

**Comment by e0** [comment]
@mihai-sysbio Do you think we would need to upgrade Docker on the prod server as well? Similar to how you did on the dev server. Just wanted to mention this here prior to the next prod deploy.

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio Do you think we would need to upgrade Docker on the prod server as well? Similar to how you did on the dev server. Just wanted to mention this here prior to the next prod deploy.

Excellent thinking! It should be part of our routines when releasing to:
- update Docker on the `dev` server (I also reboot the machine after this, but I'm not sure if that's needed)
- deploy several times to the `dev` server
- update Docker on the `prod` server
- deploy to `prod`

**Review by e0 — APPROVED** [review]
LGTM 🤞

**Pull request merged**
