### PR TITLE
feat: GotEnzymes genes index

### LINKED ISSUE #1067: GotEnzymes data includes duplicate genes
**Describe the bug**

The data used to populate the `genes` table contains duplicates. This leads to duplicate results when searching and the details page would fail to load.

**Steps to reproduce**

1. Visit `/gotenzymes`.
2. Search for `ND5`. Verify that multiple (10) results are shown in the search results.
3. Click on any of the search results. Verify that the page fails to load.

**Expected behavior**

- [ ] The input data for `genes` should be consolidated so there are no duplicates. The values for `ncbigene` and `uniprot` fields should be merged (semicolon separated and unique). See [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1062#discussion_r940074200) for more details.
- [ ] Tests verifying the fix are added

**Screenshots**

**Additional context**

Original discussion: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1062#discussion_r939975865

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #1067 and is related to #1062.

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
 
**List of changes made**  

- Update `input_data`.
- Add primary key to genes table and use single file for import.

**Screenshot of the fix**  

image

**Testing**  

- Relative urls that can be reused both for production and local testing
- Instructions on how to test
1. Replace the `input_data` with the latest updated one.
2. Visit `/gotenzymes/` and search for a gene, for example `zwf`. Verify that the response is relatively fast (hopefully under `1s`, for comparison it takes about `10s` on the dev server atm).
3. Visit a gene's details page, for example `/gotenzymes/gene/zwf`. Verify that the response is relatively fast (hopefully under `1s`, for comparison it takes about `10s` on the dev server atm).

**Further comments**  

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by mihai-sysbio — APPROVED** [review]
Looks great! I had to remove the `supplementary` folder from the path to match the `input_data`.

**Comment by e0** [comment]
> Looks great! I had to remove the `supplementary` folder from the path to match the `input_data`.

Ah sorry, I should have preserved the same folder structure before creating the zip file.

**Review by MalinAhlberg — APPROVED** [review]
Great!

Seems to be a lot faster :star:!
I also had problems with the `input_data` though, it would be nice if that folder could be updated.

**Review by inghylt — APPROVED** [review]
Great work! Also, everything runs smoothly with the db update from yesterday at 3:33 PM

**Pull request merged**
