### PR TITLE
chore: update neo4j version and create log file if necessary

### LINKED ISSUE #962: Support Apple M1
**Please describe the feature**

As a user with a Mac M1 device, I want to be able to bootstrap the project so that I can get started.

**Acceptance Criteria**

- [x] Mac M1 users should be able to get started following the README file
- [x] The web page documentation is updated accordingly
- [x] The changes are tested on multiple models and browsers

**Additional context**
On a Mac M1 when running the `build-stack` command I get 

> => ERROR [metabolicatlas_neo4j internal] load metadata for docker.io/library/neo4j:4.2.11   

> failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:216c7dcd870a6d4a6e20b839fa802c30fdeb951a79d2b4d75e618f95e1c4ed0b: not found

After adding  `platform: linux/amd64` to the neo4j section of the  docker-compose.yml I can get past this but then the import.sh script hangs: 

>  => [metabolicatlas_neo4j 5/5] RUN ./import.sh                                                                                                                                                                4429.8s
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #962..

**Type of change**  

- [x] Other
 
**List of changes made**  

- Upgrade `neo4j` version to one that's compatible with `arm64` (Apple silicon).
- Create log file (if it doesn't exist) that's needed to import data during build step.

**Testing**  

- Instructions on how to test
1. `build-stack`, verify that the build completes without any problems.
2. `start-stack`, verify that the website works as usual, for example GEMs should load on the `/explore` page.

**Further comments**  

Even though this is a targeted fix for Apple silicon, please test this on your regular development machine even if you are not using Apple silicon. This is to help ensure the change does not introduce any problems for other systems.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by inghylt** [comment]
@perjo should review this before we merge it

**Review by perjo — APPROVED** [review]
It works, great!

**Review by MalinAhlberg — APPROVED** [review]
Works well for me on my machine :1st_place_medal:

**Comment by e0** [comment]
Thanks for the reviews! Since we have confirmation from different systems (macOS and linux), I will merge this in.

**Pull request merged**
