### PR TITLE
refactor: remove obsolete map route helper

### LINKED ISSUE #631: Remove obsolete 'reload' logic for map viewer
As a developer, I would like to remove reload from query params in the map viewer, so that the project does not contain obsolete code related to this.

Related discussion: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/622#discussion_r653474913

Related files:
- `./frontend/src/components/explorer/gemBrowser/MapsAvailable.vue`
- `./frontend/src/helpers/url.js`

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #631.

**Type of change**  

- [x] Other
 
**List of changes made**  

Delete `./frontend/src/helpers/url.js` since it seems like it's not being used anywhere.

**Testing**  

- Instructions on how to test
The map viewer and rest of the site should work as before. Not sure if there is much to test here unless I missed something and `./frontend/src/helpers/url.js` was actually being used somewhere.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by MalinAhlberg** [comment]
Nice! I can't find any usage of the file, and everything seems to work as expected.
But what about o removing reload from query params, as mentioned in the issue?

**Comment by e0** [comment]
> Nice! I can't find any usage of the file, and everything seems to work as expected.
> But what about o removing reload from query params, as mentioned in the issue?

Good question! I could have been clearer about this in the PR description. It seems that all of the relevant `reload` stuff had already been removed before. The lines this issue originally was referring to belonged to the file that was removed in this PR. The remaining instances of `reload` are not related to the map viewer.

image

**Review by MalinAhlberg — APPROVED** [review]

**Review by nanjiangshu — APPROVED** [review]
Great fix! I don't see any use of `./frontend/src/helpers/url.js` in the rest of code. 
I'm curious about the mentioning of the file  
`./frontend/src/components/explorer/gemBrowser/MapsAvailable.vue` in the issue description #631. Maybe this description is out dated?

**Comment by mihai-sysbio** [comment]
> Maybe this description is out dated?

One could go back in time in the file history to see the contents at the date the issue was created.

**Comment by e0** [comment]
> I'm curious about the mentioning of the file
> `./frontend/src/components/explorer/gemBrowser/MapsAvailable.vue` in the issue description #631. Maybe this description is out dated?

In addition to what @mihai-sysbio mentioned, this is the specific commit where the last instance of `reload` was removed in that file: https://github.com/MetabolicAtlas/MetabolicAtlas/commit/831bf3abacbb1ec83bb7c22dbd61e99db799c962

Here is the comment leading up to the removal: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/622#discussion_r653610709

**Pull request merged**
