### PR TITLE
feat: code analysis

### PR DESCRIPTION
**Pull request by mihai-sysbio**
This PR integrates CodeQL through a GH Action, which then automatically highlights issues in the `Security` tab of the repository.

### CODE REVIEW

**Comment by nanjiangshu** [comment]
Hi @mihai-sysbio, I think this is a valuable addition to the professionality of our codebase. However, it will be great to see an example when an issue is highlighted as mentioned by @shan-chalmers.

**Comment by mihai-sysbio** [comment]
It looks like the details are not publicly accessible, so here are some screenshots:

image
image
image

**Comment by e0** [comment]
> It looks like the details are not publicly accessible, so here are some screenshots:

Thanks for providing the screenshots. Would the details be available for contributors of this repo?

**Review by e0 — APPROVED** [review]

**Comment by mihai-sysbio** [comment]
> Thanks for providing the screenshots. Would the details be available for contributors of this repo?

Yes, I think that's how we are supposed to make use of it.

**Pull request merged**
