### PR TITLE
fix: move sorting from frontend to backend for external-db-endpoint

### LINKED ISSUE #1309: Make sure the sorting of .../identifier/.../... is supplied by the backend API
As a user I would like the content of http://localhost/identifier/BiGG/PPNCL3 to rely on the sorting provided by the API and I would like the API to provide a sorting based on alphabetical order.

**Acceptance Criteria**
- [ ] The related API endpoint sorts the related content i alphabetical order
- [ ] The frontend no longer sorts the content supplied by the backend
- [ ] The web page documentation is updated accordingly
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

### PR DESCRIPTION
**Pull request by pdmnyberg**
**Related issue(s) and PR(s)**  
This PR closes #1309

**Type of change**  
- [x] Bug fix (non-breaking change which fixes an issue)
 
**List of changes made**  
- Sort `components` result from `/external-db/:dbName/:externalId` api endpoint
- Remove sorting from frontend component for `/identifier/:dbName/:identifierId`

**Testing**  
- Checkout and build project
- Verify that the order is correct in the frontend
- Use any tool to verify that the backend returns the components in the correct order: `curl http://localhost/api/v2/external-db/BiGG/PPNCL3 | jq`
- Run test: `ma-exec api yarn test test/externalDB.test.js`

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by jonandernovella — APPROVED** [review]

**Comment by KattisLej** [comment]
Starting review

**Review by KattisLej — APPROVED** [review]
Very good, everything looks nice, well done :)

**Comment by mihai-sysbio** [comment]
Adding that test was extra nice, well done @pdmnyberg

**Review by perjo — APPROVED** [review]
Looks very good!

**Pull request merged**
