### PR TITLE
feat: Use brotli

### PR DESCRIPTION
**Pull request by jonandernovella**
**Related issue(s) and PR(s)**  
This PR closes https://github.com/MetabolicAtlas/private-issues/issues/22

**Type of change**  

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other
 
**List of changes made**  

- Updated dockerfiles to use brotli plugin
- Added build and installation scripts

**Testing**  

- Rebuild and restart nginx (dev and prod)

### CODE REVIEW

**Review by mihai-sysbio — COMMENTED** [review]
Nice work!

The single acceptance criteria in the issue was to "Propose compression strategy to be used in the project", so since this PR is already implementing changes, I have a few discussion points before going further - perhaps easiest to take in a team discussion: 
- what is gain of brotli vs gzip
  - what do the numbers say?
- concerns about browser support:
  - are we going to drop performance for some users?
  - can multiple compression algorithms be used if one is not supported by the client?
- changes to the build process:
  - increase in build time?
  - increase in image size?
  - publishing our own base image with ghcr.io?
  - differences between `stable-` and mainline-`?
  - security implications?
- what other approaches have been considered:
  - Cloudfare?
  - any other compression service?
  - any other algorithm?

**Comment by jonandernovella** [comment]
>     * what is gain of brotli vs gzip
>    * what do the numbers say?

 https://tech.oyorooms.com/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4    

>     * concerns about browser support:
>       * are we going to drop performance for some users?
>       * can multiple compression algorithms be used if one is not supported by the client?

 I doubt there will be significant drops after looking at the benchmarks
>     * changes to the build process:
>       * increase in build time?
>       * increase in image size?
>       * publishing our own base image with ghcr.io?
The image is the same except it includes new features as well, plus the brotli binary
>       * differences between `stable-` and mainline-`?
The image is the same except it includes new features as well.
The official docs reccommend using mainline: https://www.nginx.com/blog/nginx-1-6-1-7-released/#Which-Version-Should-I-Use
>       * security implications?
Of what?
>     * what other approaches have been considered:
>       
>       * Cloudfare?
I considered that doing this on our end was better in case we decided dropping cloudflare in the future
>       * any other compression service?
No.
>       * any other algorithm?
Gzip was also tested (the previous solution)

**Review by perjo — APPROVED** [review]
Great work, LGTM

**Comment by mihai-sysbio** [comment]
Notes from the discussion (feel free to edit):

Brotli generally performs better than gzip, and is more modern. For our users, it seems faster to use some compression. For more info, see [this](https://tech.oyorooms.com/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4). There doesn't seem to be any standardized compression algorithm besides brotli.

In terms of browser support, [Brotli is well supported](https://caniuse.com/?search=brotli).

The compression part is slower than with gzip, but thanks to caching, our static assets will not incur a meaningful penalty.

Q: Are we using CPU time for compression?
Cloudfare seems to automatically run Brotli compression for us. Follow-up question: which assets?

Q: How does decompression compare for the users?
The decompression is run few times, so even if it would be a difference, it doesn't have a meaningful part.

**Pull request closed without merging**
