### PR TITLE
2.5

### PR DESCRIPTION
**Pull request by e0**
In this minor release we have focused on maintenance, fixing a number of bugs related to search and routing. General improvements for the content pages, including the <i>About</i> pages and <i>Documentation</i>, have been added as well. 

**_About_ and _Documentation_ pages**

- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/864
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/876
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/905

**Bug fixes**

- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/754
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/936
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/889
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/878
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/911
- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/800

**Misc**

- https://github.com/MetabolicAtlas/MetabolicAtlas/issues/759

This release relies on https://github.com/MetabolicAtlas/data-files/commit/504ae593d4bbe0694214ba417b160abd92f34713 and https://github.com/MetabolicAtlas/data-generation/commit/e28d3034d46b6dd8cbfe4df487c8e00b132aff6d.

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Looks good! Minor suggestions:
- `*_About_ and _Documentation_ pages*`
- `*Bug fixes*`

**Comment by nanjiangshu** [comment]
Nice work! A few comments

1. Issue #889 is duplicated 
2. Issues #759 #800 #878 are not listed

**Comment by e0** [comment]
> Looks good! Minor suggestions:
> 
> * `*_About_ and _Documentation_ pages*`
> * `*Bug fixes*`

Thanks! I have updated accordingly. Just want to mention that in 2.4 we had "Bug fixing". I agree "Bug fixes" sounds better though.

**Comment by e0** [comment]
> Nice work! A few comments
> 
> 1. Issue [Searching for PMID does not return relevant results #889](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/889) is duplicated
> 2. Issues [Description text in the API is out of date #759](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/759) [missing error messages for invalid compartments and subsystems #800](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/800) [FTP server is down #878](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/878) are not listed

That was sloppy of me. Thank you for spotting these!

**Review by nanjiangshu — APPROVED** [review]
LGTM!

**Comment by MalinAhlberg** [comment]
It seems like #800 is still missing?

**Comment by e0** [comment]
> It seems like #800 is still missing?

Thank you! Fixed now.

**Review by MalinAhlberg — APPROVED** [review]
Nice!

**Pull request merged**
