### PR TITLE
fix: source url for matomo

### PR DESCRIPTION
**Pull request by mihai-sysbio**
The url needs to contain the full path up until the `/piwik.js` suffix.

### CODE REVIEW

**Review by e0 — APPROVED** [review]
@mihai-sysbio I haven't really worked with this, don't think I have access to Matomo either but I guess you are sure of this so here is one of the mandatory approvals. 😅

**Comment by mihai-sysbio** [comment]
@e0 thanks for pointing this out. After disabling the `Do Not Track` header in your browser, by inspecting the requests on metabolicatlas.org, you can see that there is a failed request for `https://csbi.chalmers.se//piwik.js`. To double check this, you can try to request this url in a new tab - and it fails indeed. However `https://csbi.chalmers.se/matomo/piwik.js` works, which is why I just added the subpath `matomo` in url.

**Review by nanjiangshu — APPROVED** [review]
I don't know how to test this neither but feels https://csbi.chalmers.se/matomo/ should be the correct URL. Not sure how it worked with https://csbi.chalmers.se/piwik.js previously.

**Comment by mihai-sysbio** [comment]
> I don't know how to test this neither but feels https://csbi.chalmers.se/matomo/ should be the correct URL. Not sure how it worked with https://csbi.chalmers.se/piwik.js previously.

@nanjiangshu I think it was just my mistake not using the correct/full url, since `https://csbi.chalmers.se/piwik.js` has no chance of working.

**Pull request merged**
