### PR TITLE
fix: remove only project specific docker items

### LINKED ISSUE #816: restrict `clean-stack` to the MetAtlas project

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #816.

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Other
 
**List of changes made**  

Removes only Metabolic Atlas specific docker items (containers, images, and volumes) instead of all docker items for the entire system.

**Testing**  

- A rebuild is needed ~~due to new dependencies~~ if you currently don't have the project stack built
- Instructions on how to test
  1. Use the latest `proj.sh` file: `source proj.sh`.
  2. (Optional) Build and start the project if necessary: `build-stack && start-stack`.
  3. (Optional) If you don't have any other docker related items, add one to help the verification step. For example: `docker pull hello-world && docker run hello-world`.
  4. Clean the stack: `clean-stack`.
  5. Verify that the project stops running and all of the related docker items are removed and all of the non-related items are not removed: `docker image ls -a && docker ps -a`.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by e0** [comment]
For anyone interested, here is the docs page that includes information about what the different flags mean for `docker-compose down`: https://docs.docker.com/compose/reference/down/

**Review by MalinAhlberg — APPROVED** [review]
Looks good to me!

Also thanks for adding such clear descriptions on how to test :+1: !

**Review by nanjiangshu — APPROVED** [review]
Really nice to have this fix!

**Comment by mihai-sysbio** [comment]
A bit of a late comment - does this also prune the Docker volumes?

**Comment by e0** [comment]
> A bit of a late comment - does this also prune the Docker volumes?

Yea that's what the `-v` does. You can read more about it in the link mentioned here: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1002#issuecomment-1140882228

**Comment by mihai-sysbio** [comment]
Thanks @e0, I was just about to edit my comment. A bit confusing with a dangling `-v` like that. At some point I opted to switch from shorthand arguments to the long version, just because they are easier to intuitively understand when looking at commands that are not reviewed that often.

**Comment by mihai-sysbio** [comment]
I don't feel this warrants a new issue, but it could be added under the coding practices as a way to improve maintainability.

**Pull request merged**
