### PR TITLE
feat: add gotenzymes citation to landing page

### LINKED ISSUE #1228: Update citation information of GotEnzymes
**Please describe the feature**

**Acceptance Criteria**

- [ ] https://metabolicatlas.org/gotenzymes says "Manuscript under consideration", while at https://metabolicatlas.org/about/platform#citation we show how to cite the published article

**Additional context**

### PR DESCRIPTION
**Pull request by MalinAhlberg**
**Related issue(s) and PR(s)**  
This PR closes #1228.

Adds citation information to the GotEnzymes landing page.

**Type of change**  

- [x] New feature (non-breaking change which adds functionality)

 
**List of changes made**  

Added citation info with the same layout as on the About page. Please read **Further comments**  below.

**Screenshot of the fix**  

2022-11-28-130213_1108x859_scrot

**Testing**  

- Have a look at `/gotenzymes#citation` and make sure it looks good
- Also verify that `/about/platform#citation` still looks as expected.
-
**Further comments**  

- Should we use the layout from the About page, with citation widgets etc?
- Should the other publication _Deep learning-based k-cat prediction enables improved enzyme-constrained model reconstruction_, mentioned below Li F et al, still be there, and it that case, should it have the same layout? It's not a publication tied to MetabolicAtlas, so I thought it should not.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by e0 — APPROVED** [review]
Looks great @MalinAhlberg!

I saw your questions under **Further comments** as well and think the decisions you made are good. I like how things look the way they are now.

**Comment by inghylt** [comment]
Nice work!

IMO, it's a bit distracting and weird to have the citation widgets under `/gotenzymes`. I would prefer to just have them in `/about/platform`

**Comment by MalinAhlberg** [comment]
> Nice work!
> 
> IMO, it's a bit distracting and weird to have the citation widgets under `/gotenzymes`. I would prefer to just have them in `/about/platform`

I'm totally fine with not having them, too. It would look like below.

2022-11-29-084544_919x524_scrot

Any opinions from @nanjiangshu or maybe @feiranl ? @feiranl, please also feel free to have other opinions on how this section looks!

**Comment by nanjiangshu** [comment]
Nice implementation and refactoring @MalinAhlberg and @e0!

I have similar feeling as @inghylt that it's a bit redundant to have citation at the GotEnzymes page despite that it's already existing in the About page. It also makes GotEnzymes an independent tool compared to the rest on MetAtlas. Unless there is a special reason for that, e.g., someone want to specifically promote GotEnzymes, I think we can just remove the `Citation` paragraph in the GotEnzymes page. 

If the final decision is to keep the `Citation` paragraph, I can approve this PR.

**Comment by MalinAhlberg** [comment]
> Nice implementation and refactoring @MalinAhlberg and @e0!
> 
> I have similar feeling as @inghylt that it's a bit redundant to have citation at the GotEnzymes page despite that it's already existing in the About page. It also makes GotEnzymes an independent tool compared to the rest on MetAtlas. Unless there is a special reason for that, e.g., someone want to specifically promote GotEnzymes, I think we can just remove the `Citation` paragraph in the GotEnzymes page.
> 
> If the final decision is to keep the `Citation` paragraph, I can approve this PR.

Thanks for the review @nanjiangshu!
So your suggestion is to remove the whole section? If I'm not mistaken, @inghylt suggested to only remove the widgets?

**Comment by feiranl** [comment]
Hi, thanks for asking! I prefer just removing the widgets. But if you all agree that removing the whole citation part is more consistent with other part of Metabolic Atlas, then it is also ok for me :)

**Review by e0 — APPROVED** [review]
Looks good! Nice clean solution for hiding the widgets.

**Review by nanjiangshu — APPROVED** [review]
Looks great!

**Pull request merged**
