### PR TITLE
feat: make sure the same project name is used when deploying

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes https://github.com/MetabolicAtlas/private-issues/issues/139.

**Type of change**  

- [x] Other
 
**List of changes made**  
Make sure the docker compose project name is always the same.

**Further comments**  
This is a small PR and the dev team has already validated the changes.

### CODE REVIEW

**Review by nanjiangshu — APPROVED** [review]
It seems the docker compose cli does not support the syntax `docker --context remote-context compose` and I have to change it back to `docker-compose` in order to deploy to the dev server. If I remembered correctly, @MalinAhlberg has encountered a similar problem with the compose-cli on Linux as well. 

Luckily, except for that, the compose-cli seems to work at other cases, including the recent PR with linter.

**Comment by mihai-sysbio** [comment]
> It seems the docker compose cli does not support the syntax `docker --context remote-context compose` and I have to change it back to `docker-compose` in order to deploy to the dev server. If I remembered correctly, @MalinAhlberg has encountered a similar problem with the compose-cli on Linux as well.
> 
> Luckily, except for that, the compose-cli seems to work at other cases, including the recent PR with linter.

The syntax `docker --context remote-context compose` has been removed in #794, which should enable the use of the newer `docker compose` over the previous `docker-compose`. Thus, I propose to not block the merging of this PR because of this.

**Review by mihai-sysbio — APPROVED** [review]

**Review by MalinAhlberg — APPROVED** [review]
This worked perfectly for me :star:

**Comment by e0** [comment]
> It seems the docker compose cli does not support the syntax `docker --context remote-context compose` and I have to change it back to `docker-compose` in order to deploy to the dev server. If I remembered correctly, @MalinAhlberg has encountered a similar problem with the compose-cli on Linux as well. 
> 
> 
> 
> Luckily, except for that, the compose-cli seems to work at other cases, including the recent PR with linter. 
> 
> 
> 
> 

@nanjiangshu can you please try Docker compose 2.0.0 or 2.2.2 if you currently don't have one of those versions? The `proj.sh` should not need any local changes for the deploy to work.

**Comment by nanjiangshu** [comment]
> > It seems the docker compose cli does not support the syntax `docker --context remote-context compose` and I have to change it back to `docker-compose` in order to deploy to the dev server. If I remembered correctly, @MalinAhlberg has encountered a similar problem with the compose-cli on Linux as well.
> > Luckily, except for that, the compose-cli seems to work at other cases, including the recent PR with linter.
> 
> @nanjiangshu can you please try Docker compose 2.0.0 or 2.2.2 if you currently don't have one of those versions? The `proj.sh` should not need any local changes for the deploy to work.

I works with the compose cli version 2.2.2 😃 I was using `docker-compose` v2.2.2 but I actually need to upgrade the compose CLI to version 2.2.2.

**Comment by e0** [comment]
> > > It seems the docker compose cli does not support the syntax `docker --context remote-context compose` and I have to change it back to `docker-compose` in order to deploy to the dev server. If I remembered correctly, @MalinAhlberg has encountered a similar problem with the compose-cli on Linux as well.
> > > Luckily, except for that, the compose-cli seems to work at other cases, including the recent PR with linter.
> > 
> > 
> > @nanjiangshu can you please try Docker compose 2.0.0 or 2.2.2 if you currently don't have one of those versions? The `proj.sh` should not need any local changes for the deploy to work.
> 
> I works with the compose cli version 2.2.2 😃 I was using `docker-compose` v2.2.2 but I actually need to upgrade the compose CLI to version 2.2.2.

Thanks for confirming! I will merge this in then.

**Pull request merged**
