### PR TITLE
2.1

### PR DESCRIPTION
**Pull request by mihai-sysbio**
This minor release, as a `tock` release, is focused on improving the usability of the website. Some new features were added, while existing features were re-implemented and expanded. The changes are summarized below.

#### New featuress
- the _Identifier_ page is set up for all the cross-references and the Met Atlas identifiers #708 #750 
- model component counts will be always up-to-date #724
- API endpoint for map thumbnails #677 #752 

#### Feature re-implemenentation
- Data Overlay
    - it is now supporting different data types (metabolomics in addition to transcriptomics)
    - the same interface is shared between the Map Viewer and the Interaction partners #723

##### Map Viewer
- #658
- #659 
- #666 
- #695 
- #727
##### Interaction Partners 
- #660
- #703
##### GEM Browser
- #692
- #665
- show compartments in the reaction equations #743
##### Other
- #714
- visual improvement of the Advisors section #661 
- #716
- for Human-GEM, include previous (non-MA) ids in search #700
- #722

#### Misc
- #699
- #701
- #711
- #715
- #720

#### Non-code improvements
- #712 
- #713
- #717

> _Note: This release relies on https://github.com/MetabolicAtlas/data-generation/tree/e28d3034d46b6dd8cbfe4df487c8e00b132aff6d and https://github.com/MetabolicAtlas/data-files/commit/d577b55abd6b4c6650baec183c519aa8da6df7a7 ._

### CODE REVIEW

**Comment by inghylt** [comment]
Looks good!

**Comment by e0** [comment]
Good job with the release notes @mihai-sysbio! I have a question about the `data-files`, should the mock data be included in the production release? I feel like they shouldn't but they are already in the `main` branch.

**Comment by mihai-sysbio** [comment]
> I have a question about the `data-files`, should the mock data be included in the production release? I feel like they shouldn't but they are already in the `main` branch.

Very good question, it's been troubling me too. I'm wondering if we should remove any `mock` files from the production, and make sure we document this in the right issue for adding new data types. What would you suggest?

**Comment by e0** [comment]
> Very good question, it's been troubling me too. I'm wondering if we should remove any `mock` files from the production, and make sure we document this in the right issue for adding new data types. What would you suggest?

I think that sounds good. There is also the downside of having only one data type in the "Select data type" dropdown. Thinking about if we should try to hide that dropdown if there is only one data type.

**Comment by nanjiangshu** [comment]
Nice work with the release description. I have on question regarding the tags of this release for `data-files` and `data-generation`, shall we add a the tag `2.1` in the other two repos or add the commit reference in the release description in the main repo?

**Comment by mihai-sysbio** [comment]
Good idea @nanjiangshu. For now I've linked the commits from this PR. The other repos do not have any releases thus far, so let's discuss how we proceed for future releases.

**Comment by MalinAhlberg** [comment]
Looks good!

**Review by e0 — APPROVED** [review]
Would have liked more discussion on [this](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/751#issuecomment-963068878) before approving but an urgent deploy for #753 is needed so maybe we can circle back to it later.

**Review by nanjiangshu — APPROVED** [review]
Looks good to me! The tagging issue for other repos can be discussed for future releases.

**Review by MalinAhlberg — APPROVED** [review]

**Pull request merged**
