### PR TITLE
2.4

### PR DESCRIPTION
**Pull request by nanjiangshu**
In this minor release we have focused on improving the search functionality. The improvement has been achieved for both the Gem search and Global search by a better scoring of searching items and a more logical presentation of found results. More specifically, in the Gem search, the category with the highest scoring hit is ranked at the top; and in the Global search, the default tab is set as the category with the highest scoring hit. Moreover, we have resolved a number of small bugs that affected user experience. In addition, we have improved our development routine by adopting a [Definition of Done](https://en.wikipedia.org/wiki/Scrum_(software_development)#Definition_of_done_(DoD)), and an Acceptance criteria section has been added to the issue templates.

**Improving searching**
* #765
* [Improve GemSearch (quick search) layout](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/151)
* #705 
* [search pagination - research issue - decided to be implemented in the future](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/101)
* #884 
* #710 
* #744 
* #686 
* #764
* #707 
* #771 
* #729 

**Bug fixing** 
* #760 
* #759 
* #893 
* #819 
* #775 
  
**Documentation**
* #894 

**Misc**
* #790 
* #844 
* #857

### CODE REVIEW

**Review by MalinAhlberg — APPROVED** [review]
Looks good :v:

**Review by inghylt — APPROVED** [review]
Nice!

**Review by e0 — APPROVED** [review]
Looks good

**Comment by nanjiangshu** [comment]
Hi @mihai-sysbio , do you have any further comments to this PR?

**Comment by mihai-sysbio** [comment]
Thanks for the ping @nanjiangshu, looks good to me. If there's something to note, perhaps could mention:
- in general `GEM` is preferred over `Gem`
- pages or features of the website are easier to spot if they are _italicized_ and capitalized, e.g. _Global Search_

**Pull request merged**
