### PR TITLE
Test: fix api tests

### PR DESCRIPTION
**Pull request by perjo**
**Related issue(s) and PR(s)**  

Fixed failing API tests.

**Type of change**  

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other
 

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by e0 — APPROVED** [review]
Looks great! Really nice that you added the `jest/expect-expect` stuff so we don't get the unnecessary warnings any more.

**Comment by inghylt** [comment]
I think it looks good! One thing I would like to get some feedback on before approving:

- #1005 was created to
    1. Fix the broken tests
    2. Make the test more robust. 
    
       The broken tests are fixed in this PR, but this could be an opportunity to make the tests more robust as well. Note that I am fine with keeping things as is since I'd rather update some tests than miss bugs that creates erroneous data, but I suspect that there are team members with different opinions. @e0 @nanjiangshu @MalinAhlberg @perjo what are your thoughts on this?

**Comment by e0** [comment]
>   2. Make the test more robust.
>      The broken tests are fixed in this PR, but this could be an opportunity to make the tests more robust as well. Note that I am fine with keeping things as is since I'd rather update some tests than miss bugs that creates erroneous data, but I suspect that there are team members with different opinions. @e0 @nanjiangshu @MalinAhlberg @perjo what are your thoughts on this?

I think that would be a much more ambitious task. This current PR is immediately useful and is also nice to get out of the way before #1048. I'm in favor of keeping things as is.

**Comment by inghylt** [comment]
Ok! Then I'm updating #1005

**Review by inghylt — APPROVED** [review]

**Review by nanjiangshu — APPROVED** [review]
All these tests look great! 

I think we can create a new issue to solve the robustness of tests, that the tests will not break that frequently with model updates. However, I do think test condition should not be too general since otherwise it misses the meaning to catch potential mistakes. One idea could to use less frequently updated models instead of Human-GEM for specific test conditions.

**Pull request merged**
