### PR TITLE
Feature: Navigate to new route when expanding IP node to get browser history correct

### LINKED ISSUE #1168: Enable going back in IP (url)
**Please describe the feature**

As a user, I want the backward-button to work for the IP maps so that I can extend a map and then easily go back to the original one.

**Acceptance Criteria**

- [ ] Going back in browser history after having added extension works
- [ ] Going back in browser history after having added overlay works (?)
- [ ] The changes are tested on multiple models and browsers
- [ ] The changes do not reduce the performance

**Additional context**

Moved out of issue #1144

### PR DESCRIPTION
**Pull request by perjo**
**Related issue(s) and PR(s)**  
This PR closes #1168 

Changed the order of things when expanding interaction partner nodes. Instead of loading the data into the store first and trying to get routes correct later, navigate to new route first and load expansions from query params. 

**Type of change**  
- [x] New feature (non-breaking change which adds functionality)
 
**List of changes made**  

- Context action (_Expand Interaction Partners_) click navigates to new route instead of loading expansions
- On new params expansions are reset and reloaded (just as if following a deep link to this expansion state) 

Note that this could possibly affect performance as expansions are reloaded even if already present in store, but compared to production the same requests seem to be made so it seems this behavior is not changed. 

**Screenshot of the fix**  

**Testing**  

1. Go to http://localhost/explore/Human-GEM/interaction-partners
2. Right click a node and click _Expand Interaction Partners_
3. Repeat step 2
4. Go back in browser 
5. Each back step should take you to the previous expansion state.

Also test that interaction partner seem work as on https://metabolicatlas.org/explore/Human-GEM/interaction-partners in other respects. 

**Further comments**  

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by KattisLej — APPROVED** [review]
Works as expected, well done!

**Comment by pdmnyberg** [comment]
@perjo in the issue you mentioned updating the page titles in order for the history to be clearer. Did you forget do do that or did you decide it was something that should be done later on?

**Comment by perjo** [comment]
> @perjo in the issue you mentioned updating the page titles in order for the history to be clearer. Did you forget do do that or did you decide it was something that should be done later on?

Created issue #1318 for this.

**Review by pdmnyberg — APPROVED** [review]
LGTM :) Good work!

**Pull request merged**
