### PR TITLE
feat: enable all data types for custom overlays

### LINKED ISSUE #1125: Support all overlay data types for custom data, not only those that have data in the db
**Please describe the feature**

As a user, I want to be able to upload custom data for all supported data types, so that I'm not limited by only using data types belonging to the data in the db.

**Acceptance Criteria**

- [ ] Users should be able to pick any supported data type (transcriptomics, metabolomics, fluxomics) when uploading custom overlay data
- [ ] The changes are tested on multiple models and browsers

**Additional context**

Probably makes sense to use `const DATA_TYPES_COMPONENTS` in `MetabolicAtlas/frontend/src/helpers/dataOverlay.js`

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #1125.

**Type of change**  

- [x] New feature (non-breaking change which adds functionality)
 
**List of changes made**  

- Allow other data types (currently just `metabolomics`) to be selected for custom overlay data.

**Screenshot of the fix**  

image

**Testing**  

- Relative urls that can be reused both for production and local testing
- Instructions on how to test

Mock data example for `metabolomics`:

```csv
id	tissue 1	tissue 2
MAM02680m	0.6	0.3
MAM01628c	0.55	0.9
```

Mock data example for `transcriptomics`:

```csv
id	tissue 1	tissue 2
MAR01591	0.6	0.3
MAR00447	0.55	0.9
```

1. Create a couple of mock custom data files using the snippet above.
3. Use the mock custom data files to test the following scenarios. Make sure that 
     - the nodes as colored as intended, especially for `metabolomics` since it is new
     - you can remove uploaded custom files and overlay cards
     - you can copy the url, open it in another tab and that nodes are colored as expected

     i. Single overlay card, single mock file
     ii. Single overlay card, multiple mock files of different types
     iii. Single overlay card, multiple mock files of same types
     iiii. Multiple overlay cards, single mock file
     iiiii. Multiple overlay cards, multiple mock files of different types
     iiiiii. Multiple overlay cards, multiple mock files of same type
     
    Try this out on both MapViewer (2D and 3D) as well as IP. Suggested links:
    -  `/explore/Human-GEM/map-viewer/coa_synthesis?dim=2d`
    - `/explore/Human-GEM/interaction-partners/MAM02680m`

**Further comments**  
Please come up with other testing scenarios as well!

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by e0** [comment]
> I think it makes sense to keep this in a draft and wait until the refactoring of IP is done since IMO we shouldn't spend time or create custom solutions until we have the changes implemented for IP.

Sounds good!

**Comment by e0** [comment]
@inghylt Thank you for merging in `main` and adding the fixes! I tested both the map viewer and interaction partners now and they seem to work great!

**Review by MalinAhlberg — CHANGES_REQUESTED** [review]
Really great job @e0 and @inghylt!

I found two bugs and one minor issue when testing:

 - Go to a new map and apply overlay. Close and then reopene the overlay bar. The overlay in the menus and on the map will disappear. 
- Filenames get titelized (`Transcriptomics.Tsv`) in select drop down menu in Chrome (fixed in 56f3e9d)
- Use the example file to add overlay for metabolimics for http://localhost/explore/Human-GEM/map-viewer/phenylalanine_tyrosine_and_tryptophan_biosynthesis?dim=2d&panel=1&sel=MAM01139c&search=MAM01628c&coords=-1150.41,-892.18,1,792.56,261.29,-66.51&dataTypes=transcriptomics&dataSources=hpaRna.tsv&dataSets=adrenal%20gland, then remove the file while the overlay is applied. The coloring won't go away. (fixed in ddf0d3c)

**Comment by inghylt** [comment]
FYI: the discovered bug  "_Go to a new map and apply overlay. Close and then reopen the overlay bar. The overlay in the menus and on the map will disappear._" was not introduced in this PR

**Review by MalinAhlberg — APPROVED** [review]
Well done! Can't find any more bugs :)

**Review by nanjiangshu — COMMENTED** [review]
Well done! I tested with various scenarios and all work as expected. 
However, I was a bit confused with the list of data types as shown in the screenshot.

Isn't 

`gene` == `transcriptomics` 
and 
`reaction` == `fluxomics` 

according to the definition of  `DATA_TYPES_COMPONENTS` in the file `frontend//src/helpers/dataOverlay.js`? Why all of them are shown in the data type list? It seems the code from renaming of data types has not been merged to this branch yet. 

Screenshot 2022-11-02 at 10 51 41

**Comment by inghylt** [comment]
@nanjiangshu I'm not able to recreate the problems you are reporting. Since we haven't done any work yet with merging the data type renaming changes, could you try rebuilding from commit `204b4fe384bdf0f19419dac2d8c4e0ecb86ead80` in repo `data-files` and commit `9084d912c1c37f012bb09474fb7fb0bd3386cb0c` in `data-generation`?

**Comment by e0** [comment]
Had to merge `main` into this PR to resolve a conflict.

**Comment by nanjiangshu** [comment]
> @nanjiangshu ~I'm not able to recreate the problems you are reporting.~ Since we haven't done any work yet with merging the data type renaming changes, could you try rebuilding from commit `204b4fe384bdf0f19419dac2d8c4e0ecb86ead80` in repo `data-files` and commit `9084d912c1c37f012bb09474fb7fb0bd3386cb0c` in `data-generation` (i.e, the commits before the data type rename changes) and use that for testing the PR?

That explains. It looks normal now.

**Review by nanjiangshu — APPROVED** [review]
👍

**Pull request merged**
