### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by mihai-sysbio**

### CODE REVIEW

**Review by e0 — CHANGES_REQUESTED** [review]
The frontend looks fine after rebuilding and starting but I get this error for the api:

```
api         | [nodemon] starting `node dist/bundle.js`
api         | webpack:///./src/neo4j/driver.js?:14
api         | process.on('exit', /*#__PURE__*/_asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
api         |                                                                 ^
api         |
api         | ReferenceError: regeneratorRuntime is not defined
api         |     at eval (webpack:///./src/neo4j/driver.js?:14:65)
api         |     at Module../src/neo4j/driver.js (/project/dist/bundle.js:214:1)
api         |     at __webpack_require__ (/project/dist/bundle.js:20:30)
api         |     at eval (webpack:///./src/neo4j/queryHandlers/single.js?:2:70)
api         |     at Module../src/neo4j/queryHandlers/single.js (/project/dist/bundle.js:418:1)
api         |     at __webpack_require__ (/project/dist/bundle.js:20:30)
api         |     at eval (webpack:///./src/neo4j/queries/compartment.js?:2:84)
api         |     at Module../src/neo4j/queries/compartment.js (/project/dist/bundle.js:262:1)
api         |     at __webpack_require__ (/project/dist/bundle.js:20:30)
api         |     at eval (webpack:///./src/neo4j/index.js?:2:83)
api         | [nodemon] app crashed - waiting for file changes before starting...
```

**Review by nanjiangshu — COMMENTED** [review]
I got the same error for the API as @e0 when tested on Linux

**Comment by mihai-sysbio** [comment]
Thanks @e0 and @nanjiangshu for the feedback. I've tested locally and the new commit 5ba377a should address the underlying issue (`regeneratorRuntime`) without changes to `src/` as suggested by some solutions out there. Please have another look.

**Review by inghylt — APPROVED** [review]

**Review by e0 — APPROVED** [review]
Looks good! Not seeing any errors in the logs now and everything seems functional.

**Pull request merged**
