### PR TITLE
refactor: separate networks between docker containers

### PR DESCRIPTION
**Pull request by mihai-sysbio**

### CODE REVIEW

**Comment by e0** [comment]
I think this is a good idea. Is the intention to have a separate network for things that should not be accessible from outside? If that's the case I might personally prefer terminology like `public-network` and `private-network`.

**Comment by mihai-sysbio** [comment]
It's more about separating which containers can talk to each other (between themselves), essentially having multiple `private-networks`.

**Comment by e0** [comment]
Ah ok, I think I was thinking of consolidating the naming of the networks and maybe we can avoid the overwriting in the local docker compose file.

**Comment by mihai-sysbio** [comment]
The `frontend-network` in `-local` needs to be added since it only exists in the local setup, ie not in production. However, it should work just fine to add it in the base config under `networks`, even though it's used only in `-local`.

**Comment by e0** [comment]
Yea sorry, by overwriting I was thinking of the list of networks. I think I might still prefer something like a `public-network` for everything end-user facing and we can still have multiple private ones if needed. I think it is a bit easier to understand and also avoids adding a new network in the local config. That is just a personal preference though. Either way is fine.

**Pull request merged**
