### PR TITLE
feat: remove IP filter and replace with x-robots-tag

### LINKED ISSUE #860: do not index dev server
**Please describe the feature**

As a PO, I want the dev server to not be indexed so that it does not get indexed and displayed online
As a developer, I want to be able to deploy without having to comment away lines in the env-dev.env file

**Describe the solution you would like**

Replacing the current solution with something more robust, e.g. a user/pass solution

**Additional notes**
There might be another robot filter on Cloudfare in addition to the possibility of having a `robots.txt`, so I am expecting some research into this as well.

### PR DESCRIPTION
**Pull request by inghylt**
**Related issue(s) and PR(s)**  
This PR closes #860.

**Type of change**  

- [x] New feature (non-breaking change which adds functionality)
 
**List of changes made**  

- Added transform rules in Cloudflare, see below
- Deployed to dev based on this branch + with no `IP_FILTER` in the `env-dev.env` file

**Screenshot of the fix**  

image

**Testing**  

- Instructions on how to test
Use sites such as https://seositecheckup.com/tools/noindex-tag-test and https://www.seoptimer.com/noindex-tags-checker to make sure that https://dev.metabolicatlas.org is not indexed but https://metabolicatlas.org is

**Further comments**  

Based on the summary provided in https://github.com/MetabolicAtlas/MetabolicAtlas/issues/860#issuecomment-1302342163

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by e0 — APPROVED** [review]
LGTM!

Have tested the no-index tags as well.

**Review by MalinAhlberg — APPROVED** [review]
Good work :+1: !

(do we need to worry about https://dev-metatlas.csbi.chalmers.se? It currently does not send any `x-robot` tags)

**Comment by inghylt** [comment]
@MalinAhlberg ah good catch! I think it makes sense to update the rule then to use regex instead. Will post an update when that is done

**Comment by nanjiangshu** [comment]
Nice work! I think it make sense to use regular expression matches for domain names, 
1. domains starts with `dev-` should not be indexed, e.g. https://dev-metatlas.csbi.chalmers.se, https://dev-metatlas.bioshu.se
2. domains ends with `chalmers.se` should not be indexed, e.g. https://metatlas.csbi.chalmers.se, https://metatlas-prod3.csbi.chalmers.se
3. domains with IP addresses (all digits) should not be indexed, e.g. https://129.16.69.154/

**Comment by inghylt** [comment]
@MalinAhlberg @nanjiangshu 

I tried to add configuration for `dev-metatlas.csbi.chalmers.se`. Unfortunately this is not possible with current setup since we only configure the sites `metabolicatlas.com` and `metabolicatlas.org` in Cloudflare, thus the rules I specified would not affect any `.*metatlas.csbi.chalmers.se` hosts. Talked to @mihai-sysbio  about this and he said that we should not add another site to Cloudflare and it is not part of this issue to fix `dev-metatlas.csbi.chalmers.se`. It was decided to create #1215 and put it in the `Maintenance` column

**Review by nanjiangshu — APPROVED** [review]
OK. makes sense to me to address the remaining problem in the new issue.

**Pull request merged**
