### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by inghylt**
**Related issue(s) and PR(s)**  
This PR relates to #719

**Type of change**  

- [x] Other, updating frontend and api dependencies
 
**List of changes made**  

To solve the warnings from Dependabot, it made sense to update all possible dependencies as concluded in the meeting summarized here https://github.com/MetabolicAtlas/MetabolicAtlas/issues/719#issuecomment-999605191. Once verified that these updates does not break any functionality, this PR will be merged. Once the merge is finished, enable Dependabot PR:s (but not automatically merging them). If there are warnings left, we will look into the suggested PR by Dependabot

**Screenshot of the fix**  

**Testing**  

Please rebuild and test the website thoroughly to make sure that the updates does not change or break any functionality, 

**Additional comment**
- c2f7f724bb3290ad33c5cd912b1da3f502ae937b provided by @mihai-sysbio to solve the sass related problems has been cherry picked and are included in this branch. However, I chose to specify a node version in the Dockerfiles to make sure we don't have uncontrolled version updates in the future that might break functionality
- I tried to fix the warnings that are generated when you build the stack, but fixing those led to new warnings which were not straightforward to solve. There are some dependencies not updated as well because they would break functionality and was not easy to fix. But if you feel like it you are most welcome to try to fix the warnings/further update dependencies!  See the comments in #719 for some inspiration on how to do so

**Checklist**  

- [x] My changes generate no new warnings
- [x] I have checked so that the same data as before is returned by the API

### CODE REVIEW

**Comment by MalinAhlberg** [comment]
Merged with `develop`, after discussion with @inghylt

**Review by nanjiangshu — COMMENTED** [review]
Looks great @inghylt ! I tested the deployment locally and it worked well. However, the deployment to the dev server is failed. see the attached log file 
[t2.log](https://github.com/MetabolicAtlas/MetabolicAtlas/files/7931959/t2.log)

In addition, I noticed that the `node` for the `nginx/prod.Dockerfile` hasn't been updated. I guess this is because you can not test on the `prod` server.

**Review by MalinAhlberg — APPROVED** [review]
Good work :muscle: !!

From testing locally, everything seems to work well! Assuming that the problem Nanjiang pointed out is fixed, I approve.

**Review by mihai-sysbio — APPROVED** [review]
Great job @inghylt! I can also confirmed locally things are fine. Moreover, deploying to `dev` worked for me. However, there were these minor warnings that I think should be resolved, either in this issue or in another one:
```
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($timeline-header-width, 2) or calc($timeline-header-width / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
14 │ $timeline-item-padding-left: $timeline-header-width / 2 !default
   │                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bulma-timeline/src/sass/index.sass 14:30  @import
    src/App.vue 288:9                                      root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($timeline-line-width, 2) or calc($timeline-line-width / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
43 │       left: -($timeline-line-width / 2)
   │               ^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bulma-timeline/src/sass/index.sass 43:15  @import
    src/App.vue 288:9                                      root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($timeline-line-width, 2) or calc($timeline-line-width / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
136 │           right: -($timeline-line-width / 2)
    │                    ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bulma-timeline/src/sass/index.sass 136:20  @import
    src/App.vue 288:9                                       root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($timeline-header-width, 2) or calc($timeline-header-width / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
174 │       margin-right: $timeline-header-width / 2
    │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bulma-timeline/src/sass/index.sass 174:21  @import
    src/App.vue 288:9                                       root stylesheet
    ```

**Comment by nanjiangshu** [comment]
For the problem (as mentioned in [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/850#pullrequestreview-861956479)) to deploy to the `dev` server, as discussed by Ingrid and Nanjiang, one solution would be deleting the folder `frontend/node_modules` on the local repo and re-deploy.

**Review by nanjiangshu — APPROVED** [review]
👍

**Comment by e0** [comment]
> Great job @inghylt! I can also confirmed locally things are fine. Moreover, deploying to `dev` worked for me. However, there were these minor warnings that I think should be resolved, either in this issue or in another one:

Added [a commit](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/850/commits/05713028ec118773bb42a1c978ae5143aa945e2b) that fixes now. Good timing for us as it looks like this was fixed in the library 10 days ago: https://github.com/Wikiki/bulma-timeline/issues/63

**Review by e0 — APPROVED** [review]
Seems to run great on my local machine and dev server. Good job!

**Comment by e0** [comment]
I think we can ignore the failing prettier check for now. I didn't merge in everything from `develop` and just fixed the dependencies. The prettier check should pass once this is merged into `develop`.

**Comment by inghylt** [comment]
@e0 has done a great job fixing the warnings and merge conflicts with the develop branch. The develop branch is now fully merged with this branch and have been tested locally as well as deployed to the dev machine to make sure everything stills works as expected. I would like to merge this branch since both me and @e0 have verified that the latest changes are ok. Please give this a thumbs up if you are fine with that or else make a comment

**Comment by inghylt** [comment]
And also, kudos to @MalinAhlberg and @nanjiangshu as well for their work with PR :star: Team effort this one!

**Comment by e0** [comment]
Thank you for being so kind @inghylt! Also wanted to mention that I got quite flustered yesterday with a docker related problem and had to re-build things a few times. But that was so brief compared to all the inconvenience you dealt with when working on this issue. Thanks for taking the lead on this and it should help streamline this type of work in the future.

**Pull request merged**
