### PR TITLE
feat: add list of compartments to gene details for the HPA endpoint

### PR DESCRIPTION
**Pull request by e0**
This closes https://github.com/MetabolicAtlas/private-issues/issues/107

### CODE REVIEW

**Comment by e0** [comment]
The compartments are returned in the following format. To make it easy for HPA to link to us if they wish to.

image

**Comment by mihai-sysbio** [comment]
Looks good, but I'll test before formally approving.

**Review by mihai-sysbio — CHANGES_REQUESTED** [review]
Something seems to be off with the underlying query, or with the data generation. Looking at [`CTSA`](http://localhost/api/v2/hpa/gene/ENSG00000064601) the only compartment should be `Lysosome`. However, `Cystosol` is also returned. This seems to be consistent with the information provided in the GEM Browser. However, when trying to validate this with the Map Viewer, none of the five 2D maps for Cytosol have `CTSA`, which is consistent with manually finding the text `CTSA` in the plainted SVGs. In the 3D viewer `CTSA` seems to be present in the Cytosol.

**Comment by e0** [comment]
> Looks good! I'm wondering though if the correct issue is linked in the PR description?

Thanks! Corrected it now.

**Comment by e0** [comment]
> Something seems to be off with the underlying query, or with the data generation. Looking at [`CTSA`](http://localhost/api/v2/hpa/gene/ENSG00000064601) the only compartment should be `Lysosome`. However, `Cystosol` is also returned. This seems to be consistent with the information provided in the GEM Browser. However, when trying to validate this with the Map Viewer, none of the five 2D maps for Cytosol have `CTSA`, which is consistent with manually finding the text `CTSA` in the plainted SVGs. In the 3D viewer `CTSA` seems to be present in the Cytosol.

Interesting observation. Looking at the related reactions for this gene it looks like the following reaction is the culprit.

`/explore/Human-GEM/gem-browser/reaction/MAR05259`

Either way, this looks like a potential bug for the data-files repo right?

**Comment by mihai-sysbio** [comment]
> Either way, this looks like a potential bug for the data-files repo right?

Upon further inspection, the observation is fully in line with the source Human-GEM `yml`, so no issue needs to be reported at this time.

**Review by mihai-sysbio — APPROVED** [review]
Nice job!

**Pull request merged**
